### ISSUE TITLE
"unexpected tSTRING_BEG"

### ISSUE THREAD

**Issue by tukkek** [Berlioz/Enkibot#2]
I've created and ran a launcher with the usage example in the Read Me file and got this error:

```
Traceback (most recent call last):
        1: from ./launcher.rb:2:in `<main>'
./launcher.rb:2:in `load': generator.rb:28: syntax error, unexpected tSTRING_BEG, expecting '}' (SyntaxError)
    "Cannoneer" => "CAN",
    ^
generator.rb:28: syntax error, unexpected =>, expecting keyword_end
    "Cannoneer" => "CAN",
                ^~
generator.rb:28: syntax error, unexpected ',', expecting keyword_end
    "Cannoneer" => "CAN",
                        ^
generator.rb:29: syntax error, unexpected =>, expecting keyword_end
    "Gladiator" => "GLD",
                ^~
generator.rb:29: syntax error, unexpected ',', expecting keyword_end
    "Gladiator" => "GLD",
                        ^
generator.rb:30: syntax error, unexpected =>, expecting keyword_end
    "Oracle" => "ORC"
             ^~
generator.rb:31: syntax error, unexpected '}', expecting keyword_end
```

This is my `launcher.rb`file:

```ruby
#!/usr/bin/ruby
load 'generator.rb'
generator=Generator.new(['Knight','Red-Mage','Ranger','Chemist'])
print generator.get_walkthrough
```

**Comment by tukkek** [comment]
The version I'm running is a simple `git clone` of the current repository status.

**Comment by Berlioz** [comment]
Apologies; I'd kind of forgotten about this side project. Should be fixed now.
